// Code generated by Kitex v0.3.1. DO NOT EDIT.

package likeservice

import (
	"context"
	"fmt"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	"github.com/cloudwego/kitex/pkg/streaming"
	"github.com/hh02/minimal-douyin/kitex_gen/likerpc"
	"google.golang.org/protobuf/proto"
)

func serviceInfo() *kitex.ServiceInfo {
	return likeServiceServiceInfo
}

var likeServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "LikeService"
	handlerType := (*likerpc.LikeService)(nil)
	methods := map[string]kitex.MethodInfo{
		"CreateLike": kitex.NewMethodInfo(createLikeHandler, newCreateLikeArgs, newCreateLikeResult, false),
		"GetUser":    kitex.NewMethodInfo(getUserHandler, newGetUserArgs, newGetUserResult, false),
		"MGetUser":   kitex.NewMethodInfo(mGetUserHandler, newMGetUserArgs, newMGetUserResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "like",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.3.1",
		Extra:           extra,
	}
	return svcInfo
}

func createLikeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(likerpc.CreateLikeRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(likerpc.LikeService).CreateLike(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *CreateLikeArgs:
		success, err := handler.(likerpc.LikeService).CreateLike(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateLikeResult)
		realResult.Success = success
	}
	return nil
}
func newCreateLikeArgs() interface{} {
	return &CreateLikeArgs{}
}

func newCreateLikeResult() interface{} {
	return &CreateLikeResult{}
}

type CreateLikeArgs struct {
	Req *likerpc.CreateLikeRequest
}

func (p *CreateLikeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in CreateLikeArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *CreateLikeArgs) Unmarshal(in []byte) error {
	msg := new(likerpc.CreateLikeRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateLikeArgs_Req_DEFAULT *likerpc.CreateLikeRequest

func (p *CreateLikeArgs) GetReq() *likerpc.CreateLikeRequest {
	if !p.IsSetReq() {
		return CreateLikeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateLikeArgs) IsSetReq() bool {
	return p.Req != nil
}

type CreateLikeResult struct {
	Success *likerpc.CreateLikeResponse
}

var CreateLikeResult_Success_DEFAULT *likerpc.CreateLikeResponse

func (p *CreateLikeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in CreateLikeResult")
	}
	return proto.Marshal(p.Success)
}

func (p *CreateLikeResult) Unmarshal(in []byte) error {
	msg := new(likerpc.CreateLikeResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateLikeResult) GetSuccess() *likerpc.CreateLikeResponse {
	if !p.IsSetSuccess() {
		return CreateLikeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateLikeResult) SetSuccess(x interface{}) {
	p.Success = x.(*likerpc.CreateLikeResponse)
}

func (p *CreateLikeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func getUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(likerpc.DeleteLikeRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(likerpc.LikeService).GetUser(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *GetUserArgs:
		success, err := handler.(likerpc.LikeService).GetUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserResult)
		realResult.Success = success
	}
	return nil
}
func newGetUserArgs() interface{} {
	return &GetUserArgs{}
}

func newGetUserResult() interface{} {
	return &GetUserResult{}
}

type GetUserArgs struct {
	Req *likerpc.DeleteLikeRequest
}

func (p *GetUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in GetUserArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserArgs) Unmarshal(in []byte) error {
	msg := new(likerpc.DeleteLikeRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserArgs_Req_DEFAULT *likerpc.DeleteLikeRequest

func (p *GetUserArgs) GetReq() *likerpc.DeleteLikeRequest {
	if !p.IsSetReq() {
		return GetUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserArgs) IsSetReq() bool {
	return p.Req != nil
}

type GetUserResult struct {
	Success *likerpc.DeleteLikeResponse
}

var GetUserResult_Success_DEFAULT *likerpc.DeleteLikeResponse

func (p *GetUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in GetUserResult")
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserResult) Unmarshal(in []byte) error {
	msg := new(likerpc.DeleteLikeResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserResult) GetSuccess() *likerpc.DeleteLikeResponse {
	if !p.IsSetSuccess() {
		return GetUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*likerpc.DeleteLikeResponse)
}

func (p *GetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func mGetUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(likerpc.QueryLikeByUserIdRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(likerpc.LikeService).MGetUser(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *MGetUserArgs:
		success, err := handler.(likerpc.LikeService).MGetUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*MGetUserResult)
		realResult.Success = success
	}
	return nil
}
func newMGetUserArgs() interface{} {
	return &MGetUserArgs{}
}

func newMGetUserResult() interface{} {
	return &MGetUserResult{}
}

type MGetUserArgs struct {
	Req *likerpc.QueryLikeByUserIdRequest
}

func (p *MGetUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in MGetUserArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *MGetUserArgs) Unmarshal(in []byte) error {
	msg := new(likerpc.QueryLikeByUserIdRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var MGetUserArgs_Req_DEFAULT *likerpc.QueryLikeByUserIdRequest

func (p *MGetUserArgs) GetReq() *likerpc.QueryLikeByUserIdRequest {
	if !p.IsSetReq() {
		return MGetUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *MGetUserArgs) IsSetReq() bool {
	return p.Req != nil
}

type MGetUserResult struct {
	Success *likerpc.QueryLikeByUserIdResponse
}

var MGetUserResult_Success_DEFAULT *likerpc.QueryLikeByUserIdResponse

func (p *MGetUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in MGetUserResult")
	}
	return proto.Marshal(p.Success)
}

func (p *MGetUserResult) Unmarshal(in []byte) error {
	msg := new(likerpc.QueryLikeByUserIdResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *MGetUserResult) GetSuccess() *likerpc.QueryLikeByUserIdResponse {
	if !p.IsSetSuccess() {
		return MGetUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *MGetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*likerpc.QueryLikeByUserIdResponse)
}

func (p *MGetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateLike(ctx context.Context, Req *likerpc.CreateLikeRequest) (r *likerpc.CreateLikeResponse, err error) {
	var _args CreateLikeArgs
	_args.Req = Req
	var _result CreateLikeResult
	if err = p.c.Call(ctx, "CreateLike", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUser(ctx context.Context, Req *likerpc.DeleteLikeRequest) (r *likerpc.DeleteLikeResponse, err error) {
	var _args GetUserArgs
	_args.Req = Req
	var _result GetUserResult
	if err = p.c.Call(ctx, "GetUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MGetUser(ctx context.Context, Req *likerpc.QueryLikeByUserIdRequest) (r *likerpc.QueryLikeByUserIdResponse, err error) {
	var _args MGetUserArgs
	_args.Req = Req
	var _result MGetUserResult
	if err = p.c.Call(ctx, "MGetUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
