// Code generated by Kitex v0.3.1. DO NOT EDIT.

package videoservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/hh02/minimal-douyin/kitex_gen/videorpc"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateVideo(ctx context.Context, Req *videorpc.CreateVideoRequest, callOptions ...callopt.Option) (r *videorpc.CreateVideoResponse, err error)
	MGetVideo(ctx context.Context, Req *videorpc.MGetVideoRequest, callOptions ...callopt.Option) (r *videorpc.MGetVideoResponse, err error)
	QueryVideoByUserId(ctx context.Context, Req *videorpc.QueryVideoByUserIdRequest, callOptions ...callopt.Option) (r *videorpc.QueryVideoByUserIdResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) CreateVideo(ctx context.Context, Req *videorpc.CreateVideoRequest, callOptions ...callopt.Option) (r *videorpc.CreateVideoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateVideo(ctx, Req)
}

func (p *kVideoServiceClient) MGetVideo(ctx context.Context, Req *videorpc.MGetVideoRequest, callOptions ...callopt.Option) (r *videorpc.MGetVideoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MGetVideo(ctx, Req)
}

func (p *kVideoServiceClient) QueryVideoByUserId(ctx context.Context, Req *videorpc.QueryVideoByUserIdRequest, callOptions ...callopt.Option) (r *videorpc.QueryVideoByUserIdResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryVideoByUserId(ctx, Req)
}
