// Code generated by Kitex v0.3.1. DO NOT EDIT.

package commentservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/hh02/minimal-douyin/kitex_gen/commentrpc"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateComment(ctx context.Context, Req *commentrpc.CreateCommentRequest, callOptions ...callopt.Option) (r *commentrpc.CreateCommentResponse, err error)
	DeleteComment(ctx context.Context, Req *commentrpc.DeleteCommentRequest, callOptions ...callopt.Option) (r *commentrpc.DeleteCommentResponse, err error)
	QueryCommentByVideo(ctx context.Context, Req *commentrpc.QueryCommentByVideoIdRequest, callOptions ...callopt.Option) (r *commentrpc.QueryCommentByVideoIdResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentServiceClient struct {
	*kClient
}

func (p *kCommentServiceClient) CreateComment(ctx context.Context, Req *commentrpc.CreateCommentRequest, callOptions ...callopt.Option) (r *commentrpc.CreateCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateComment(ctx, Req)
}

func (p *kCommentServiceClient) DeleteComment(ctx context.Context, Req *commentrpc.DeleteCommentRequest, callOptions ...callopt.Option) (r *commentrpc.DeleteCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteComment(ctx, Req)
}

func (p *kCommentServiceClient) QueryCommentByVideo(ctx context.Context, Req *commentrpc.QueryCommentByVideoIdRequest, callOptions ...callopt.Option) (r *commentrpc.QueryCommentByVideoIdResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryCommentByVideo(ctx, Req)
}
