// Code generated by Kitex v0.3.1. DO NOT EDIT.

package publishservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/hh02/minimal-douyin/cmd/publish/kitex_gen/douyin/core"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PublishList(ctx context.Context, Req *core.PublishListRequest, callOptions ...callopt.Option) (r *core.PublishListResponse, err error)
	PublishAction(ctx context.Context, Req *core.PublishActionRequest, callOptions ...callopt.Option) (r *core.PublishActionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPublishServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPublishServiceClient struct {
	*kClient
}

func (p *kPublishServiceClient) PublishList(ctx context.Context, Req *core.PublishListRequest, callOptions ...callopt.Option) (r *core.PublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishList(ctx, Req)
}

func (p *kPublishServiceClient) PublishAction(ctx context.Context, Req *core.PublishActionRequest, callOptions ...callopt.Option) (r *core.PublishActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishAction(ctx, Req)
}
